baseURL = "https://chenzongshu.github.io/"
languageCode = "zh-CN"
title = "蜗牛龙门阵"
theme = "maupassant"
## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
summaryLength = 8 # 列表页面上帖子描述的长度。

[author]
  name = "chenzongshu"

[params]
  author = "chenzongshu"
  subtitle = "专注容器等IT技术"
  keywords = "golang,java,博客,项目管理"
  description = "摆一摆技术,聊一聊江湖"
  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = false  # 是否开启目录

[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"
